
version: "3.1"

services:

    db:
      image: aditi/mysql
      environment: 
             MYSQL_ROOT_PASSWORD: root
             MYSQL_DATABASE: test 
             MYSQL_USER: root

    demo:
      image: aditi/demo
      deploy:
         replicas: 3
      ports:
         - 8012:8080
      depends_on:
         - db
